[build-libs][hyperswitch-gradle-plugin]

diff --git a/.github/workflows/gradle-publish.yml b/.github/workflows/gradle-publish.yml
--- a/.github/workflows/gradle-publish.yml
+++ b/.github/workflows/gradle-publish.yml
@@ -39,21 +39,57 @@ jobs:
         server-password: MAVEN_PASSWORD
         gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
         gpg-passphrase: GPG_PASSPHRASE
+
+
     
     - name: Extract libraries from commit message
       id: extract-libs
       run: |
+          # Extract text between square brackets after [build-libs]
           COMMIT_MSG="${{ github.event.head_commit.message }}"
+          LIBS=$(echo "$COMMIT_MSG" | grep -o '\[build-libs\]\[.*\]' | grep -o '\[.*\]$' | tr -d '[]')
+          if [ -z "$LIBS" ]; then
+            echo "No libraries specified in commit message"
+            exit 1
+          fi
+          echo "Found libraries: $LIBS"
+          echo "libraries=$LIBS" >> $GITHUB_OUTPUT
+      
+          # COMMIT_MSG="${{ github.event.head_commit.message }}"
           
-          # Check if commit message contains a valid format for libraries
-          # if [[ "$COMMIT_MSG" =~ ^release:\ \[([a-zA-Z0-9, ]+)\]\ .* ]]; then
-            LIBS="${BASH_REMATCH[1]}"
-            echo "Found libraries: $LIBS"
-            echo "libraries=$LIBS" >> $GITHUB_OUTPUT
-          # else
-            # echo "No valid libraries found in commit message"
-            # exit 1
-          # fi
+          # # Check if commit message contains a valid format for libraries
+          # # if [[ "$COMMIT_MSG" =~ ^release:\ \[([a-zA-Z0-9, ]+)\]\ .* ]]; then
+          #   LIBS="${BASH_REMATCH[1]}"
+          #   echo "Found libraries: $LIBS"
+          #   echo "libraries=$LIBS" >> $GITHUB_OUTPUT
+          # # else
+          #   # echo "No valid libraries found in commit message"
+          #   # exit 1
+          # # fi
+
+    - name: Dependency Install
+      run: |
+        # Create a new folder for the dependencies
+        mkdir -p /home/runner/work/hyperswitch-sdk-android
+        cd /home/runner/work/hyperswitch-sdk-android
+        
+        # Download package.json from GitHub
+        curl -o package.json -L https://raw.githubusercontent.com/juspay/hyperswitch-client-core/main/package.json
+        
+        # Modify package.json (if needed)
+        jq 'del(.resolutions) | 
+            del(.dependencies["react-native-hyperswitch-netcetera-3ds"]) | 
+            del(.dependencies["react-native-hyperswitch-scancard"])' package.json > package.json.tmp && 
+            mv package.json.tmp package.json
+
+        # Install dependencies using yarn
+        yarn
+        
+        # Check if the necessary build folder exists, otherwise fail
+        if [ ! -d "node_modules/@react-native/gradle-plugin" ]; then
+          echo "Included build 'node_modules/@react-native/gradle-plugin' does not exist."
+          exit 1
+        fi      
     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
   
